apiVersion: v1
kind: Pod
metadata:
  name: downward-env
spec:
  containers:
    - name: main
      image: ghcr.io/jungminii/downward_api:master
      # other configuration details
  imagePullSecrets:
    - name: ${{ secrets.GHCR_PAT }}
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
